#!/bin/sh
set -e
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    useradd --user-group -M --system dvmhost --shell /bin/false || true
    usermod --groups dialout --append dvmhost || true
    #chown dvmhost:dvmhost /opt/dvm/iden_table.dat
    #chown dvmhost:dvmhost /opt/dvm/rid_acl.dat
    #chown dvmhost:dvmhost /opt/dvm/tg_acl.dat
    #chown dvmhost:dvmhost /opt/dvm/log

    git clone https://github.com/Centrunk/centrunk_tools.git /opt/centrunk

    rm -rf /.git*


fi