daemon: true
log:
    displayLevel: 1
    fileLevel: 1
    filePath: .
    activityFilePath: .
    fileRoot: DVM
network:
    enable: true
    id: 100000
    address: 127.0.0.1
    port: 62031
    rconEnable: false
    rconAddress: 127.0.0.1
    rconPort: 9990
    rconPassword: "PASSWORD"
    rconDebug: false
    jitter: 360
    password: "PASSWORD"
    slot1: true
    slot2: true
    updateLookups: false
    allowActivityTransfer: false
    allowDiagnosticTransfer: false
    debug: false
protocols:
    dmr:
        enable: true
        beacons:
            enable: false
            interval: 60
            duration: 3
        control: 
            dedicated: false
            enable: false
            slot: 1
        embeddedLCOnly: false
        dumpTAData: true
        dumpDataPacket: false
        repeatDataPacket: true
        dumpCsbkData: false
        callHang: 5
        txHang: 8
        silenceThreshold: 21
        queueSize: 5000
        verbose: true
        debug: false
    p25:
        enable: true
        tduPreambleCount: 6
        control:
            enable: false
            ackRequests: true
            dedicated: false
            broadcast: true
            interval: 300
            duration: 1
        voiceOnControl: false
        disableCompositeFlag: false
        inhibitIllegal: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        verifyAff: false
        verifyReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 5
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: true
        silenceThreshold: 124
        disableNetworkHDU: false
        queueSize: 5000
        verbose: true
        debug: false
system:
    identity: ABCD123
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 10
#    rfModeHang: 10
#    netModeHang: 10
#    fixedMode: false
    rfTalkgroupHang: 10
    info:
        latitude: -83.689428
        longitude: -39.194973
        height: 1
        power: 10
        location: "Repeater Site, Antarctica"
    config:
        channelId: 2
        channelNo: 1
        dmrNetId: 1
        voiceChNo:
            - 1
        colorCode: 1
        nac: 293
#         txNAC: 293
        pSuperGroup: FFFF
        netId: BB800
        sysId: 001
        rfssId: 1
        siteId: 1
    modem:
        protocol:
            type: "null" # Valid values are "null", "uart", and "udp"
            uart:
                port: /dev/ttyUSB0
                speed: 115200
            udp:
                mode: master # Valid values are "master", and "peer"
                endpointAddress: 0.0.0.0
                port: 3334
        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 80
        dmrRxDelay: 7
        p25CorrCount: 8
        dmrDiscBWAdj: 0 # Valid values between -128 and 128
        dmrPostBWAdj: 0 # Valid values between -128 and 128
        p25DiscBWAdj: 0 # Valid values between -128 and 128
        p25PostBWAdj: 0 # Valid values between -128 and 128
        adfGainMode: 0 # 0 - Auto, 1 - Auto High Lin, 2 - Low, 3 - High
        dmrSymLvl3Adj: 0 # Valid values between -128 and 128
        dmrSymLvl1Adj: 0 # Valid values between -128 and 128
        p25SymLvl3Adj: 0 # Valid values between -128 and 128
        p25SymLvl1Adj: 0 # Valid values between -128 and 128
        rxDCOffset: 0 # Valid values between -128 and 128
        txDCOffset: 0 # Valid values between -128 and 128
        txTuning: 0 # Freq offset for the hotspot, in hz
        rxTuning: 0
        rxLevel: 50
        txLevel: 50
#        cwIdTxLevel: 50
#        dmrTxLevel: 50
#        p25TxLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        trace: false
        debug: false
    cwId:
        enable: true
        time: 15
        callsign: ABCD123
    iden_table:
        file: iden_table.dat
        time: 30
    radio_id:
        file: rid_acl.dat
        time: 2
        acl: false
    talkgroup_id:
        file: tg_acl.dat
        time: 2
        acl: false
